version: "3.3"
name: bitcoind-testnet3
services:
  testnet3:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: oneforalonee/bitcoind:v26.0
    container_name: bitcoind-testnet3
    hostname: testnet3
    command: >-
      bitcoind -server=1 -chain=test
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28335
      -zmqpubrawtx=tcp://0.0.0.0:28336 -zmqpubhashblock=tcp://0.0.0.0:28337
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18332 -rest -listen=1 -listenonion=0
    volumes:
      - ./bitcoin:/home/bitcoin/.bitcoin
    expose:
      - "18332"
      - "28335"
      - "28336"
    ports:
      - "18332:18332"
      - "28335:28335"
      - "29336:28336"
