version: "3.3"
name: bitcoin-core
services:
  testnet3:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: oneforalonee/bitcoind:v26.0
    container_name: bitcoind
    hostname: bitcoind
    command: >-
      bitcoind -server=1 -chain=main
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333 -zmqpubhashblock=tcp://0.0.0.0:28334
      -txindex=1 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=8332 -rest -listen=1 -listenonion=0
    volumes:
      - ./bitcoin:/home/bitcoin/.bitcoin
    expose:
      - "8332"
      - "28332"
      - "28333"
    ports:
      - "8332:8332"
      - "28332:28332"
      - "29333:28333"
