version: "3.3"
name: bitcoind-regnet
services:
  regnet:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: oneforalonee/bitcoind:v26.0
    container_name: bitcoind-regnet
    hostname: regnet
    command: >-
      bitcoind -server=1 -chain=regtest
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28338
      -zmqpubrawtx=tcp://0.0.0.0:28339 -zmqpubhashblock=tcp://0.0.0.0:28340
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18334 -rest -listen=1 -listenonion=0
    volumes:
      - ./bitcoin:/home/bitcoin/.bitcoin
    expose:
      - "18334"
      - "28338"
      - "28339"
    ports:
      - "18334:18334"
      - "28338:18338"
      - "28339:18339"
