version: "3.3"
name: bitcoind-testnet3
services:
  testnet3:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: oneforalonee/bitcoind:v26.0
    container_name: bitcoind-testnet3
    hostname: testnet3
    command: >-
      bitcoind -server=1 -chain=signet
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18334 -rest -listen=1 -listenonion=0
    volumes:
      - ./bitcoin:/home/bitcoin/.bitcoin
    expose:
      - "18334"
      - "28334"
      - "28335"
    ports:
      - "18334:18334"
      - "28334:28334"
      - "29335:28335"
